# Generated by Django 4.0 on 2024-11-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='題名')),
                ('description', models.TextField(verbose_name='内容')),
                ('deadline', models.DateField(verbose_name='期限')),
                ('coupon', models.CharField(max_length=50, verbose_name='クーポン')),
                ('requester', models.CharField(max_length=100, verbose_name='依頼者名')),
                ('prefecture', models.CharField(max_length=50, verbose_name='都道府県')),
                ('payment', models.CharField(max_length=50, verbose_name='支払い方法')),
            ],
        ),
    ]
