# Generated by Django 4.0 on 2024-11-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('requester', models.CharField(max_length=100)),
                ('prefecture', models.CharField(max_length=50)),
                ('payment', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='QuestRequest',
        ),
    ]
