# Generated by Django 4.0 on 2024-11-25 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_questregister_alter_quest_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questregister',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='questregister',
            name='reward',
        ),
        migrations.AddField(
            model_name='quest',
            name='reward',
            field=models.CharField(default=1, max_length=3),
        ),
        migrations.AddField(
            model_name='questregister',
            name='quest_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quest_registers', to='formapp.quest', verbose_name='クエストID'),
        ),
    ]
