# Generated by Django 5.1.3 on 2024-11-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_questregister_alter_quest_payment_and_more'),
    ]

