# Generated by Django 5.1.2 on 2024-11-25 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_remove_questregister_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questregister',
            name='quest_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='quest_registers', to='formapp.quest', verbose_name='クエストID'),
        ),
    ]
