# Generated by Django 5.1.2 on 2024-11-25 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0005_alter_questregister_quest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questregister',
            name='quest_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quest_registers', to='formapp.quest', verbose_name='クエストID'),
        ),
    ]
