# Generated by Django 5.1.2 on 2024-11-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0006_alter_questregister_quest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='questregister',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questregister',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
