# Generated by Django 5.1.3 on 2024-11-26 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_questregister_latitude_questregister_longitude'),
        ('formapp', '0007_questregister_latitude_questregister_longitude'),
    ]

    operations = [
    ]
