# Generated by Django 5.1.3 on 2024-11-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('requester', models.CharField(max_length=100)),
                ('prefecture', models.CharField(max_length=50)),
                ('payment', models.CharField(max_length=50)),
            ],
        ),
    ]
