# Generated by Django 5.1.3 on 2024-11-26 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0008_merge_20241126_1233'),
        ('userquest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_id', models.AutoField(primary_key=True, serialize=False, verbose_name='クーポンID')),
                ('coupon_description', models.TextField(null=True, verbose_name='クーポン詳細')),
                ('used_at', models.DateTimeField(verbose_name='使用期限')),
                ('quest_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formapp.quest', verbose_name='クエストID')),
            ],
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('user_coupon_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ユーザークーポンID')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='発行日時')),
                ('coupon_status', models.BooleanField(default=False, verbose_name='ステータス')),
                ('coupon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userquest.coupon', verbose_name='クーポンID')),
                ('user_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
        ),
    ]
